import { papers } from './data.js';
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key = 'geopolymer.workspace.v1';
export function readDrafts(storage) {
 const raw = storage.getItem(key);
 if (!raw) return [];
 const data = JSON.parse(raw);
 if (!Array.isArray(data) || data.some(x => !x || typeof x.id !== 'string' || typeof x.title !== 'string' || typeof x.body !== 'string')) throw new Error('Saved drafts could not be read. Existing data has been kept.');
 return data;
}
export function saveDraft(storage, draft) {
 if (!draft.title.trim() || !draft.body.trim()) throw new Error('Add a title and notes before saving.');
 const rows = readDrafts(storage);
 const record = {...draft,title:draft.title.trim(),body:draft.body.trim(),updatedAt:new Date().toISOString()};
 const index = rows.findIndex(x=>x.id===record.id);
 if(index<0) rows.unshift(record); else rows[index]=record;
 storage.setItem(key,JSON.stringify(rows));
 return rows;
}
const go=(url,title)=>`<a class="text-link" href="${url}">${title} →</a>`;
const intro=(k,t,b)=>`<section class="page-intro"><p class="eyebrow">${k}</p><h1>${t}</h1><p class="lede">${b}</p></section>`;
export function platformPage(area) {
 if(area==='workspace') return intro('MY WORKSPACE','Turn observations into knowledge.','Keep an experiment, formulation, study submission or discussion draft. Saved on this browser only; download a copy to keep or share.')+`<div class="workspace-grid"><aside class="side-panel"><h2>Your drafts</h2><button id="new-draft" class="button secondary">New draft</button><div id="draft-list"></div></aside><form id="draft-form" class="record"><input type="hidden" name="id"><label>Record type<select name="kind"><option>Experiment</option><option>Formulation</option><option>Study submission</option><option>Discussion</option><option>Supply request</option><option>Magazine pitch</option></select></label><label>Title<input name="title" required maxlength="180"></label><label>Source DOI or URL<input name="source" maxlength="500" placeholder="Optional source reference"></label><label>Materials, grades and quantities<textarea name="materials" rows="3" placeholder="Record exact grade, lot, units and whether a mass is dry or as supplied."></textarea></label><label>Method, observations and limitations<textarea name="body" rows="10" required placeholder="Question; preparation; cure; test age and method; results with units; uncertainty; what remains unknown."></textarea></label><label>Image references / captions<textarea name="images" rows="2" placeholder="Record image URLs and captions. Image uploads and shared storage are not connected yet."></textarea></label><div class="actions"><button class="button" type="submit">Save draft</button><button class="button secondary" type="button" id="download-draft">Download draft</button></div><p id="draft-status" role="status"></p><p class="small">Drafts are private to this browser and can be lost if browser data is cleared. Saving does not submit, publish or request peer review.</p></form></div>`;
 if(area==='discover') return intro('RESEARCH CATALOG','Find the evidence behind the material.','Search the curated catalog by title, author or DOI. Source access and review status stay visible.')+`<form class="search-form" id="paper-search"><label class="sr-only" for="paper-query">Search studies</label><input id="paper-query" type="search" placeholder="Material, author, title or DOI"><button class="button">Search studies</button></form><p class="small">${papers.length} curated record available. We are building the catalog; this is not a comprehensive literature search.</p><p><a class="button secondary" href="/library">Browse dozens of recent papers →</a></p><div id="paper-results" aria-live="polite">${papers.map(p=>`<article class="record"><h2>${go("/research/"+p.id,esc(p.title))}</h2><p>${esc(p.authors)}</p><p>${esc(p.summary)}</p><p>${esc(p.access)}</p></article>`).join("")}</div><section class="evidence-band"><div><h2>Contribute your research.</h2><p>Prepare your methods, material records, results and limitations for editorial assessment.</p></div>${go('/workspace?kind=Study%20submission','Prepare a submission')}</section>${go('/review','How review will work')}`;
 if(area==='review') return intro('RESEARCH INTEGRITY','Review that readers can inspect.','Proposed review process. Reviewer recruitment, submissions and public reviews are not live yet.')+`<div class="grid three">${[['01 / EDITORIAL CHECK','Make the record complete','Check authorship, disclosure, source rights, grades, method, data availability and scope before inviting reviewers.'],['02 / EXPERT REVIEW','Review the evidence','Invite at least two relevant reviewers, check conflicts, and record reproducibility, methods and interpretation concerns.'],['03 / REVISION','Keep the history','Authors respond point by point. An editor records the decision and publishes accepted versions with review scope and corrections.']].map(([k,t,b])=>`<article class="record"><p class="eyebrow">${k}</p><h2>${t}</h2><p>${b}</p></article>`).join('')}</div><div class="callout">Community comments, platform peer review, journal peer review and independent laboratory testing are different statuses. An uploaded recipe will never acquire a reviewed badge automatically.</div><section class="section"><h2>What a submission should include</h2><p>Research question · exact grades and lots · ingredient masses and basis · activator specification · mixing and cure · specimen geometry · test standard and age · raw results and uncertainty · photographs and permissions · limitations · funding and conflicts.</p>${go('/workspace?kind=Study%20submission','Prepare your research draft')}</section>`;
 if(area==='community') return intro('COMMUNITY / IN DEVELOPMENT','Work together. Keep the evidence connected.','Planned spaces for scientists, students, artists and material developers. No public posts or accounts are active yet.')+`<div class="grid three">${[['Research & replication','Compare protocols, ask about missing method details and document replication attempts.'],['Classroom & learning','Share lesson plans, observations and student questions.'],['Art & fabrication','Discuss cast forms, color studies, textured surfaces and studio trials.'],['Materials & sourcing','Compare specifications, sample needs and regional supply questions.'],['Troubleshooting','Describe a result with its materials, method, photos and limits.'],['Collaboration','Develop a project brief and identify the expertise or testing you need.']].map(([t,b])=>`<article class="record"><h2>${t}</h2><p>${b}</p>${go('/workspace?kind=Discussion','Draft a discussion')}</article>`).join('')}</div>`;
 if(area==='journal') return intro('MAGAZINE & PODCAST / PLANNED','A monthly window into material science.','Research explained clearly, studio experiments documented carefully, and conversations with the people doing the work.')+`<div class="grid two"><article class="record"><p class="eyebrow">PROPOSED FIRST ISSUE</p><h2>From paper to practice.</h2><p>A guide to reading a formulation, a classroom observation activity, an artist’s sample notebook and a material sourcing checklist.</p><p class="small">Editorial outline only. No issue has been published.</p>${go('/workspace?kind=Magazine%20pitch','Draft an article pitch')}</article><article class="record"><p class="eyebrow">PROPOSED PODCAST</p><h2>Inside the material lab.</h2><p>Conversations about reproducibility, regional raw materials, teaching and the path from experimental sample to useful product.</p><p class="small">Guests and recordings are not scheduled.</p>${go('/workspace?kind=Magazine%20pitch','Propose a topic or guest')}</article></div>`;
 if(area==='supply') return intro('SUPPLY PLANNING','From a first sample to a production batch.','Browse proposed supply categories and prepare a purchasing brief. Stock, bulk pricing and shipping are not yet available.')+`<div class="grid three">${[['Samples & learning','Small precursor samples, starter kits and classroom refills.','/shop'],['Studio & workshop','Casting systems, pigments, aggregates and surface studies.','/shop?audience=artists'],['Research & production','Grade-specific bags, pallet quantities and bulk supply requests.','/workspace?kind=Supply%20request']].map(([t,b,u])=>`<article class="record"><h2>${t}</h2><p>${b}</p>${go(u,'Explore')}</article>`).join('')}</div><section class="section"><h2>Prepare a supply request</h2><p>Include material and grade, quantity and unit, destination country/postcode, intended use, required documentation and unloading facilities. Save the brief as a supply-request draft; it is not sent to a supplier.</p>${go('/workspace?kind=Supply%20request','Create supply brief')}</section><div class="callout">Global research access is the goal. Physical delivery eligibility will be established by product and destination; international shipping is not currently offered.</div>`;
 return '';
}
export function attachPlatform(area) {
 if(area==='discover') {
 const input=document.querySelector('#paper-query'); input.value=new URLSearchParams(location.search).get('q')||'';
 const run=()=>{const words=input.value.toLowerCase().trim().split(/\s+/).filter(Boolean);const found=papers.filter(p=>words.every(w=>`${p.title} ${p.authors} ${p.doi} ${p.summary}`.toLowerCase().includes(w)));document.querySelector('#paper-results').innerHTML=found.length?found.map(p=>`<article class="record"><p class="eyebrow">${esc(p.year)} / ${esc(p.publication)}</p><h2>${go('/research/'+p.id,esc(p.title))}</h2><p>${esc(p.authors)}</p><p>${esc(p.summary)}</p><p class="small">${esc(p.access)} · DOI ${esc(p.doi)}</p></article>`).join(''):'<div class="empty">No matching studies in the current catalog. Try a broader term.</div>';};
 input.addEventListener('input',run);document.querySelector('#paper-search').addEventListener('submit',e=>{e.preventDefault();run();});run();
 }
 if(area!=='workspace') return;
 const form=document.querySelector('#draft-form'), status=document.querySelector('#draft-status');
 const fields=['id','kind','title','source','materials','body','images'];
 const clear=()=>{form.reset();form.elements.id.value=crypto.randomUUID(); const kind=new URLSearchParams(location.search).get('kind');if([...form.elements.kind.options].some(o=>o.value===kind))form.elements.kind.value=kind;status.textContent='New draft. Not saved yet.';};
 const render=()=>{const rows=readDrafts(localStorage);document.querySelector('#draft-list').innerHTML=rows.length?rows.map(r=>`<button type="button" class="draft-item" data-draft="${esc(r.id)}"><strong>${esc(r.title)}</strong><span>${esc(r.kind)}</span></button>`).join(''):'<p>No saved drafts yet.</p>';document.querySelectorAll('[data-draft]').forEach(b=>b.onclick=()=>{if((form.elements.title.value||form.elements.body.value)&&!confirm('Open another draft? Save current edits first if you want to keep them.'))return;const row=rows.find(r=>r.id===b.dataset.draft);fields.forEach(k=>form.elements[k].value=row[k]||'');status.textContent='Opened saved draft.';});};
 form.addEventListener('submit',e=>{e.preventDefault();try{saveDraft(localStorage,Object.fromEntries(fields.map(k=>[k,form.elements[k].value])));render();status.textContent='Saved on this browser. Not published.';}catch(e){status.textContent='Could not save: '+e.message;}});
 document.querySelector('#new-draft').onclick=()=>{if((form.elements.title.value||form.elements.body.value)&&!confirm('Start a new draft? Save current edits first if you want to keep them.'))return;clear();};
 document.querySelector('#download-draft').onclick=()=>{const d=Object.fromEntries(fields.map(k=>[k,form.elements[k].value]));const blob=new Blob([JSON.stringify({format:'geopolymer-draft-v1',...d},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='geopolymer-draft.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent='Draft downloaded. Not submitted.';};
 clear();try{render();}catch(e){status.textContent=e.message;}
}
