import { researchUpdates } from "./research-updates.js";
// Publisher-indexed discovery metadata checked 2026-10-03. Not full-paper reviews.
// Year follows the cited publication/issue year; online-first dates may differ.
const records = [
[2026,'Preparation and Anti-Corrosion Properties of Hydrophobic Geopolymer Coatings','10.3390/coatings16070752','Coatings','Coatings','Research article'],
[2026,'Activator-to-Binder Ratio–Driven Microstructural and Interfacial Performance Optimization of Metakaolin-Based Geopolymer Coatings','10.3390/coatings16070825','Coatings','Coatings','Research article'],
[2026,'Rapidly Synthesized Microwave-Sintered Geopolymer Foam Utilizing Granite Waste: A Sustainable Approach for High-Performance Construction Materials','10.3390/su18104754','Sustainability','Foams & thermal','Research article'],
[2026,'Phosphate-Activated Fayalite-Based Geopolymer Foam','10.3390/ceramics9070071','Ceramics','Alternative activation','Research article'],
[2026,'Thermal Insulation and Compressive Strength of Lightweight Geopolymer Foam Concrete Exposed to Accelerated Weathering by Carbonation, Salt Fog and UV Light','10.3390/ma19010012','Materials','Foams & thermal','Research article'],
[2026,'Synthesis and characterization of geopolymer foam based on construction and demolition waste','10.1016/j.susmat.2026.e01875','Sustainable Materials and Technologies','Foams & thermal','Research article'],
[2026,'Experimental study on multi-objective performance of geopolymer foam building insulation material using a novel industrial-scale fabrication method','10.1016/j.conbuildmat.2026.145501','Construction and Building Materials','Foams & thermal','Research article'],
[2026,'Unveiling the Coating Effect of Magnesium-Bearing Precipitates on the Rheology of Metakaolin-Based Geopolymer','10.1111/jace.71116','Journal of the American Ceramic Society','Mix design & chemistry','Research article'],
[2026,'Used Coffee Grounds as Fine Aggregate in Lightweight Geopolymer Composites: Influence on Engineering Properties and Microstructures','10.58845/jstt.utt.2026.en.6.2.187-205','Journal of Science and Transport Technology','Waste & biomass','Research article'],
[2026,'Upcycling spent coffee grounds into biochar-reinforced geopolymer mortars: sustainable structural materials with enhanced mechanical performance','10.1080/19648189.2025.2594582','European Journal of Environmental and Civil Engineering','Waste & biomass','Research article'],
[2026,'Geopolymerization: A novel method for manufacturing tiles from copper mine tailings','10.1016/j.rineng.2026.111040','Results in Engineering','Art, casting & fabrication','Research article'],
[2025,'Degradation Potential of Metakaolin-Based Geopolymer Composites Immersed in Real and Simulated Acidic Environments','10.3390/su17020468','Sustainability','Durability','Research article'],
[2025,'Effects of EOGO in Metakaolin-Based Geopolymer','10.3390/ma18163864','Materials','Mix design & chemistry','Research article'],
[2025,'Characterization and Selection of Metakaolin for Reproducible Geopolymer Matrices: A Thermal Evolution Approach','10.3390/jne6030034','Eng','Mix design & chemistry','Research article'],
[2025,'Improving Drying Shrinkage Performance of Metakaolin-Based Geopolymers by Adding Cement','10.3390/buildings15101650','Buildings','Durability','Research article'],
[2025,'Development of lightweight architecture of geopolymer via extrusion-based 3D printing for CO2 capture','10.1016/j.jeurceramsoc.2025.117191','Journal of the European Ceramic Society','3D printing','Research article'],
[2025,'Impact of different mixing temperature on the microstructural evolution and properties of metakaolin-based geopolymers','10.1016/j.clay.2025.108106','Applied Clay Science','Mix design & chemistry','Research article'],
[2025,'Exploring the formation of phosphoric acid-based metakaolin geopolymer and underlying mechanisms under various Liquid-to-Solid ratios','10.1016/j.jssc.2025.125607','Journal of Solid State Chemistry','Alternative activation','Research article'],
[2025,'Metakaolin-based single-step engineered geopolymer composites: Design and performance characterization','10.1016/j.clay.2025.108055','Applied Clay Science','Mix design & chemistry','Research article'],
[2025,'Geopolymers as a sustainable alternative to Portland cement: Synthesis, durability, applications, environmental impacts, and cost analysis','10.1016/j.rser.2025.116157','Renewable and Sustainable Energy Reviews','Sustainability','Review article'],
[2025,'Mechanical and durability performance of metakaolin and fly ash-based geopolymers compared to cement systems','10.1016/j.rineng.2025.105788','Results in Engineering','Durability','Research article'],
[2025,'Metakaolin-based geopolymer matrix formulations for higher strength and thermal stability','10.1617/s11527-025-02670-5','Materials and Structures','Mix design & chemistry','Research article'],
[2025,'Structural Study of Metakaolin-Phosphate Geopolymers Prepared with Wide Range of Al/P Molar Ratios','10.3390/polym17172358','Polymers','Alternative activation','Research article'],
[2025,'Development of cost-effective geopolymer mortars from low-grade metakaolin and bottom ash for 3D construction printing','10.1002/suco.70093','Structural Concrete','3D printing','Research article'],
[2025,'Using XRD to Assess the Strength of Fly-Ash- and Metakaolin-Based Geopolymers','10.3390/ma18092093','Materials','Characterization','Research article'],
[2025,'Advances and developments in high strength geopolymer concrete for sustainable construction – A review','10.1016/j.cscm.2025.e04669','Case Studies in Construction Materials','Sustainability','Review article'],
[2024,'Durability of low-carbon geopolymer concrete: A critical review','10.1016/j.susmat.2024.e00882','Sustainable Materials and Technologies','Durability','Review article'],
[2024,'A critical review of the advancements in acid-activated metakaolin geopolymers','10.1016/j.conbuildmat.2024.135609','Construction and Building Materials','Alternative activation','Review article'],
[2024,'Preparation of functional geopolymers from municipal solid waste incineration fly ash: An approach combining experimental and computational simulation studies','10.1016/j.jenvman.2024.120226','Journal of Environmental Management','Waste & biomass','Research article'],
[2024,'Durability and microstructural evolution of high-performance ecological geopolymer concrete under low-pressure–salt-erosion–freeze–thaw cycling conditions','10.1016/j.conbuildmat.2024.136197','Construction and Building Materials','Durability','Research article'],
[2024,'Multi-performance optimization of low-carbon geopolymer considering mechanical, cost, and CO2 emission based on experiment and interpretable learning','10.1016/j.conbuildmat.2024.136013','Construction and Building Materials','Sustainability','Research article'],
[2024,'Upscaling of Copper Slag-Based Geopolymer to 3D Printing Technology','10.3390/ma17225581','Materials','3D printing','Research article'],
[2024,'Towards Sustainable Material: Optimizing Geopolymer Mortar Formulations for 3D Printing: A Life Cycle Assessment Approach','10.3390/su16083328','Sustainability','3D printing','Research article'],
[2024,'Advanced Refinement of Geopolymer Composites for Enhanced 3D Printing via In-Depth Rheological Insights','10.3390/ceramics7040087','Ceramics','3D printing','Research article'],
[2024,'Printhead mixing of geopolymer and OPC slurries for hybrid alkali-activated cement in 3D concrete printing','10.1016/j.conbuildmat.2024.136439','Construction and Building Materials','3D printing','Research article'],
[2024,'Performance modulation and optimization of PE fiber reinforced 3D-printed geopolymer','10.1016/j.conbuildmat.2024.136449','Construction and Building Materials','3D printing','Research article'],
[2017,'Mix design factors and strength prediction of metakaolin-based geopolymer','10.1016/j.ceramint.2017.06.006','Ceramics International','Foundations','Research article'],
[2003,'Chemical optimisation of the compressive strength of aluminosilicate geopolymers synthesised by sodium silicate activation of metakaolinite','10.1039/B212629J','Journal of Materials Chemistry','Foundations','Research article'],
[2019,'Standardized Method in Testing Commercial Metakaolins for Geopolymer Formulations','10.13140/RG.2.2.18109.10727/1','Geopolymer Institute · Technical Paper #26','Foundations','Technical report']
];
const existing = records.map(([year,title,doi,journal,topic,type],i)=>({id:'library-'+(i+1),year,title,doi,journal,topic,type,url:'https://doi.org/'+doi,checked:'2026-10-03',access:'Publisher-indexed metadata; full-paper review pending'}));
export const library=[...existing,...researchUpdates];
export function filterLibrary(query='',year='all',topic='all',type='all',scope='all',sort='newest'){
 const words=query.toLowerCase().trim().split(/\s+/).filter(Boolean);
 const rows=library.filter(r=>(year==='all'||String(r.year)===year)&&(topic==='all'||r.topic===topic)&&(type==='all'||r.type===type)&&(scope!=='summaries'||!!r.summary)&&words.every(w=>`${r.title} ${r.doi} ${r.journal} ${r.topic} ${r.year} ${r.authors||''} ${r.summary||''} ${(r.highlights||[]).join(' ')}`.toLowerCase().includes(w)));
 return rows.sort(sort==='title'?(a,b)=>a.title.localeCompare(b.title):(a,b)=>(b.published||String(b.year)).localeCompare(a.published||String(a.year))||a.title.localeCompare(b.title));
}
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const options=values=>values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');
export function libraryResults(rows=filterLibrary()){return rows.length?rows.map(r=>`<article class="record library-card" id="${esc(r.id)}"><div class="library-meta"><span>${r.published?`<time datetime="${r.published}">${r.published}</time>`:r.year}</span><span>${esc(r.type)}</span><span>${esc(r.topic)}</span></div><h2>${esc(r.title)}</h2><p>${esc(r.journal)}${r.authors?` · ${esc(r.authors)}`:''}</p>${r.summary?`<p class="library-summary">${esc(r.summary)}</p><details><summary>Highlights &amp; evidence</summary><ul>${r.highlights.map(h=>`<li>${esc(h)}</li>`).join('')}</ul><p class="small">${esc(r.publicationStatus)} · ${esc(r.dateBasis)}.</p><p class="small">${esc(r.summaryAuthor)}. ${esc(r.summaryBasis)}. Checked ${r.checked}.</p></details>`:''}<p class="small">${esc(r.access)}${r.type==='Technical report'?' · Journal peer review not established.':''}</p><p class="small">DOI: ${esc(r.doi)}</p><div class="actions"><a class="text-link" target="_blank" rel="noopener noreferrer" href="${esc(r.publisherUrl||r.url)}">Read at publisher ↗</a><a class="text-link" href="/calculator?source=${encodeURIComponent(r.id)}">Link to formulation study →</a></div></article>`).join(''):'<div class="empty">No matching references. Broaden your keywords or reset the filters.</div>';}
export function libraryPage(){return `<section class="page-intro"><p class="eyebrow">RESEARCH / SEARCHABLE DATABASE</p><h1>A growing library of geopolymer research.</h1><p class="lede">${library.length} source-linked references. Twenty new September–October 2026 papers, with brief original summaries and research highlights.</p><p>Browse recent studies, reviews and foundational work. This is a curated selection of recent publications verified on 10 October 2026, not an exhaustive ranking of every new paper. Read full articles at their publishers.</p><div class="actions"><a class="text-link" href="/journal">Read the research briefings →</a><a class="text-link" href="/research-library.json" download>Download database JSON ↓</a></div></section><form class="library-controls" id="library-form"><label class="sr-only" for="lib-query">Search titles, summaries, authors, topics, journals or DOI</label><input type="search" id="lib-query" placeholder="Topic, summary, author, title or DOI"><select id="lib-year" aria-label="Publication year"><option value="all">All years</option>${options([...new Set(library.map(r=>r.year))].sort((a,b)=>b-a))}</select><select id="lib-topic" aria-label="Research topic"><option value="all">All topics</option>${options([...new Set(library.map(r=>r.topic))].sort())}</select><select id="lib-type" aria-label="Publication type"><option value="all">All publication types</option>${options([...new Set(library.map(r=>r.type))])}</select><select id="lib-scope" aria-label="Record coverage"><option value="all">All references</option><option value="summaries">New papers with summaries</option></select><select id="lib-sort" aria-label="Sort references"><option value="newest">Newest first</option><option value="title">Title A–Z</option></select><button class="button">Search</button><button type="button" class="button secondary" id="lib-clear">Reset</button></form><p class="library-count" id="lib-count" role="status">${library.length} of ${library.length} references</p><div class="grid two" id="lib-results">${libraryResults()}</div><div class="callout">Summaries and highlights are short, original AI-assisted discovery notes, not publisher abstracts or independent validation. New records use verified publication/online dates; older records retain their cited year. Early-access articles and reviews are labeled. Journal publication is not platform peer review or independent replication. Follow the publisher for full methods, corrections and access terms; some articles require a subscription.</div><section class="section"><h2>Bring a source into your work.</h2><p>Record exact materials, ratio definitions and test conditions before comparing results. Acid/phosphate studies are outside the current calculator’s alkaline-oxide model.</p><div class="actions"><a class="button" href="/calculator">Open GP calculator</a><a class="button secondary" href="/workspace?kind=Study%20submission">Draft a study record</a></div></section>`;}
export function attachLibrary(){const q=s=>document.querySelector(s);const run=()=>{const rows=filterLibrary(q('#lib-query').value,q('#lib-year').value,q('#lib-topic').value,q('#lib-type').value,q('#lib-scope').value,q('#lib-sort').value);q('#lib-count').textContent=`${rows.length} of ${library.length} references`;q('#lib-results').innerHTML=libraryResults(rows);};q('#lib-query').value=new URLSearchParams(location.search).get('q')||'';q('#library-form').onsubmit=e=>{e.preventDefault();run();};q('#lib-query').oninput=run;['#lib-year','#lib-topic','#lib-type','#lib-scope','#lib-sort'].forEach(s=>q(s).onchange=run);q('#lib-clear').onclick=()=>{q('#library-form').reset();run();};run();}
