// Original discovery summaries. Primary publisher records checked 10 October 2026.
// Dates are publication/online availability, not issue dates. No full texts/images republished.
const records = [
['pp-impact','2026-10-09','Dynamic Compressive Behavior and Internal Damage Evolution of Polypropylene Fiber-Reinforced Alkali-Activated Slag Geopolymer Mortar','10.3390/ma19204263','Materials','Fibers & mechanics','https://www.mdpi.com/1996-1944/19/20/4263','Binghui Cui, Yanzhu Liu and Liang Wang','Research article','Published; DOI registration pending at check',
 'Impact tests examine how polypropylene fibers change the response of slag-based mortar under rapid loading.',
 ['Fiber content and loading rate both affect the reported response.','Dynamic impact results should not be substituted for static strength tests.']],
['nickel-carbon','2026-10-08','Geopolymer-Derived Aluminosilicate Matrix Composites Reinforced with Continuous Nickel-Coated Carbon Fibers: Tensile Properties and Thermo-Oxidative Behavior','10.3390/polym18192448','Polymers','Fibers & mechanics','https://www.mdpi.com/2073-4360/18/19/2448','Michal Jasiczek, Marcelina Bobrowska and Arnold Jedral','Research article','Published',
 'This feasibility study examines continuous carbon-fiber laminates with an inorganic matrix, including tensile behavior and changes during thermal oxidation.',
 ['Compares different fiber layups.','Specialized laminate processing limits direct transfer to ordinary mortar.']],
['soft-clay','2026-10-08','Strength and stiffness development of one-part fly ash-bottom ash geopolymer stabilized soft clay','10.1038/s41598-026-73492-w','Scientific Reports','Soil stabilization','https://www.nature.com/articles/s41598-026-73492-w','Zhongqing Chen and Yue Lyu','Research article','Early-access accepted article',
 'A dry-activated fly ash and bottom ash binder is investigated for improving soft clay, with attention to strength development, stiffness, cost and emissions.',
 ['The ash blend is a key experimental variable.','Soil-treatment results are distinct from cast-concrete performance.']],
['brick-sand','2026-10-01','Synergistic effect of silica sand particle size on the compressive strength and pore structure of geopolymers prepared from recycled fired clay brick waste','10.1007/s44290-026-00639-z','Discover Civil Engineering','Waste & biomass','https://link.springer.com/article/10.1007/s44290-026-00639-z','Cédric Mbiakop Dieuhou and colleagues','Research article','Published',
 'The researchers vary silica sand fineness in recycled-brick binders and relate the resulting strength to pore structure.',
 ['The finest sand was not automatically the best-performing addition.','Precursor heat treatment also changes the comparison.']],
['tensile-curing','2026-10-01','The Preparation of the Engineered Geopolymer Composites and Their Tensile Strain Capacity Research','10.3390/civileng7040066','CivilEng','Fibers & mechanics','https://www.mdpi.com/2673-4109/7/4/66','Qiwei Wang, Chao Xu and Dingtao Yang','Research article','Published',
 'Fly ash composite tests track how fiber reinforcement and curing temperature influence tensile strength, deformation and multiple cracking.',
 ['Strength gain and deformation capacity do not follow identical trends.','Imaging is used to examine crack development during testing.']],
['nano-models','2026-09-29','Quantitative analysis and modeling of mechanical properties of geopolymer concrete incorporating nanomaterials','10.1007/s44290-026-00622-8','Discover Civil Engineering','AI & modeling','https://link.springer.com/article/10.1007/s44290-026-00622-8','Yasmin Hefni Abdel Aziz and Taha A. El-Sayed','Research article','Published',
 'A literature-based analysis tests whether compressive strength alone can estimate other mechanical properties of nanomaterial-modified geopolymer composites.',
 ['The fitted relationships have limited predictive strength.','Flexure and stiffness need property-specific evidence and validation.']],
['mgo-phosphate','2026-09-29','Preparation and Reaction Mechanism of Ambient-Cured Silico-Aluminate Phosphate Geopolymer Modified by Magnesium Oxide','10.1016/j.jobe.2026.117456','Journal of Building Engineering','Alternative activation','https://www.sciencedirect.com/science/article/pii/S2352710226022783','Hui Lin, Jianhang Hu, Xiongfei Liu, Jiale Shen and Yue Li','Research article','In press; journal pre-proof',
 'An ambient-cured metakaolin, magnesium oxide and phosphate system is studied for its reaction pathway, workability and mechanical performance.',
 ['Reaction heat helps the system cure at room temperature.','This phosphate chemistry is outside our alkaline-oxide calculator model.']],
['ceramic-activator','2026-09-27','Ceramic Waste Powder-Derived Dry Activator for Sustainable One-Part Fly Ash-Based Geopolymer Mortars','10.3390/buildings16193834','Buildings','One-part binders','https://www.mdpi.com/2075-5309/16/19/3834','Seemab Tayyab, Wahid Ferdous, Weena Lokuge, Tuan Ngo, Andreas Gerdes and Allan Manalo','Research article','Published',
 'Ceramic waste is chemically and thermally processed into a solid activator, then evaluated in fly ash mortar as a proof of concept.',
 ['Activator preparation conditions substantially affect the resulting mortar.','Processing energy belongs in any environmental comparison.']],
['volcanic-graphene','2026-09-23','Sustainable Graphene-Reinforced Geopolymer Composites Derived from Recycled Volcanic Ash: Matrix Optimization, Characterization, and Photoluminescent Proof-of-Concept','10.3390/polym18192322','Polymers','Art, casting & fabrication','https://www.mdpi.com/2073-4360/18/19/2322','Luigi Madeo and colleagues','Research article','Published',
 'A volcanic-ash matrix is combined with graphene additions and a separate light-emitting coating to explore a multifunctional composite.',
 ['Matrix modification and coating function are separate design questions.','A proof of concept does not establish exterior service life.']],
['coupled-durability','2026-09-22','Durability Degradation Mechanisms and Coupled Deterioration Behaviors of Geopolymer Concrete Under Multi-Hazard Service Environments: A Critical Review','10.3390/ma19194050','Materials','Durability','https://www.mdpi.com/1996-1944/19/19/4050','Jiale Li, Fei Yang, Ran Hai, Wenhao Mi and Cun Hui','Review article','Published',
 'This review considers how binder chemistry and interacting environmental exposures influence deterioration, distinguishing low-calcium geopolymers from calcium-rich activated materials.',
 ['Exposure combinations matter when interpreting durability tests.','A high initial compressive strength is not a service-life rating.']],
['red-mud-composites','2026-09-17','A Study on the Mechanical Properties of Engineered Geopolymer Composites Based on Red Mud, Fly Ash, and Slag','10.3390/polym18182271','Polymers','Fibers & mechanics','https://www.mdpi.com/2073-4360/18/18/2271','','Research article','Published',
 'Ten binder blends are compared to study how red mud, fly ash and slag affect flow, compression and tensile behavior.',
 ['Uses a planned mixture experiment rather than a single blend.','Fresh-state flow and hardened behavior are evaluated together.']],
['red-mud-rice','2026-09-15','Reaction mechanism and compressive strength of geopolymer based on the synergistic excitation of red mud and rice husk ash','10.3389/fmech.2026.1946182','Frontiers in Mechanical Engineering','Waste & biomass','https://www.frontiersin.org/journals/mechanical-engineering/articles/10.3389/fmech.2026.1946182/full','Yuyi Liu, Qin Yang, Jiayu Xu, Yuxiang Li, Siyu Dai, Xu Liu, Qichao Zhu and Changsheng Geng','Research article','Published',
 'The study examines a binder combining red mud with rice husk ash, connecting reaction behavior with measured compression performance.',
 ['Pairs an industrial residue with an agricultural ash.','Source-specific chemistry is essential when comparing these residues.']],
['mineralogy-wastes','2026-09-13','Mineralogy-Guided Processing of Mining and Metallurgical Wastes into Geopolymeric and Alkali-Activated Materials','10.3390/min16090936','Minerals','Waste & biomass','https://www.mdpi.com/2075-163X/16/9/936','','Review article','Published',
 'A review organizes waste-processing choices around mineral phases and their accessibility to reaction, rather than bulk oxide totals alone.',
 ['Mineralogy helps explain why chemically similar wastes behave differently.','Processing choices need to follow the actual precursor.']],
['brick-thermal','2026-09-12','High-Temperature Behavior and Mechanical Performance of Ceramic Brick and Metakaolin Waste Based-Geopolymer Binder','10.3390/ma19183890','Materials','Foams & thermal','https://www.mdpi.com/1996-1944/19/18/3890','','Research article','Published',
 'Waste-derived brick and metakaolin binders are examined before and after heating to connect mechanical changes with matrix chemistry.',
 ['Studies both precursor selection and thermal exposure.','Residual properties after heating differ from initial room-temperature strength.']],
['sensor-bricks','2026-09-12','Development and performance evaluation of wollastonite–fly ash geopolymer bricks with embedded IoT sensors for strength monitoring','10.1007/s43939-026-00911-0','Discover Materials','Monitoring & characterization','https://link.springer.com/article/10.1007/s43939-026-00911-0','','Research article','Published',
 'Wollastonite and fly ash bricks are studied alongside embedded temperature monitoring during curing.',
 ['Uses an embedded temperature sensor and a Raspberry Pi.','Temperature monitoring is not itself a direct strength measurement.']],
['co2-aggregate','2026-09-11','Sustainable valorization of CO₂-treated recycled fine aggregates in one-part geopolymer mortars: Mechanical, thermal, and durability performance','10.1016/j.rineng.2026.112967','Results in Engineering','Durability','https://www.sciencedirect.com/science/article/pii/S2590123026039794','E.S. Poojalakshmi and colleagues','Research article','In press; journal pre-proof',
 'Recycled fine aggregate is treated with silica and carbon dioxide before use in a one-part mortar, with several performance measures assessed.',
 ['The authors report improved aggregate–binder interfaces.','Treatment and binder composition both affect transfer to other mixtures.']],
['hsom-strength','2026-09-09','A simulation of hierarchical self organizing maps to predict the compressive strength of fly ash-based geopolymers','10.1038/s41598-026-68752-8','Scientific Reports','AI & modeling','https://www.nature.com/articles/s41598-026-68752-8','Siaw Hui Teo, Herry Prabowo, Wui Lee Chang and Idawati Ismail','Research article','Early-access accepted article',
 'An experimental dataset is used to compare hierarchical and conventional self-organizing maps for compressive-strength estimation.',
 ['The reported dataset contains 18 distinct mix proportions.','Repeated measurements are not equivalent to hundreds of independent recipes.']],
['fem-review','2026-09-08','A systematic review of finite element modeling of geopolymer and alkali activated cement systems for sustainable structural design','10.1007/s43939-026-00764-7','Discover Materials','AI & modeling','https://link.springer.com/article/10.1007/s43939-026-00764-7','Prabhjot Singh, Harpal Singh, Raman Kumar, Rajender Kumar and Abhijit Bhowmik','Review article','Early-access accepted article',
 'A review of numerical and experimental studies examines structural models, interface behavior and how predictions are checked against tests.',
 ['Calibration must reflect the binder and structural system.','Model transfer across different chemistries remains a limitation.']],
['pumice-thermal','2026-09-08','High-Temperature Performance of Metakaolin-Based Geopolymer Recycled Mortar with Pumice Powder','10.3390/ma19183819','Materials','Foams & thermal','https://www.mdpi.com/1996-1944/19/18/3819','','Research article','Published',
 'The paper examines thermal damage and remaining mechanical properties in metakaolin recycled mortar containing pumice powder.',
 ['Connects aggregate selection with behavior after heating.','Consult the original exposure and test conditions before comparison.']],
['cao-onepart','2026-09-07','Effect of Calcium Oxide on the Mechanical and Structural Properties of Metakaolin-Based One-Part Geopolymer','10.3390/molecules31173132','Molecules','One-part binders','https://www.mdpi.com/1420-3049/31/17/3132','','Research article','Published',
 'Different calcium oxide additions are tested in a dry metakaolin system, with strength development linked to structural characterization.',
 ['The reported strength response to increasing CaO is non-monotonic.','Adding calcium should not be treated as a universal strength boost.']]
];
export const researchUpdates = records.map(([slug,published,title,doi,journal,topic,publisherUrl,authors,type,publicationStatus,summary,highlights])=>({
 id:'research-'+slug,year:2026,published,dateBasis:'Publisher publication / online-availability date',title,doi,journal,topic,publisherUrl,authors,type,publicationStatus,summary,highlights,
 url:'https://doi.org/'+doi,checked:'2026-10-10',added:'2026-10-10',summaryBasis:'Publisher abstract or indexed publisher overview; full methods not audited',
 access:'Read the source for full methods, current version and access terms',summaryAuthor:'Geopolymer Platform · AI-assisted discovery note'
}));

// Reviewed daily additions; original draft retained in research-drafts for provenance.
researchUpdates.push({
  "year": 2026,
  "dateBasis": "Publisher version-of-record publication date",
  "type": "Research article",
  "publicationStatus": "Published; version of record",
  "checked": "2026-10-10",
  "added": "2026-10-10",
  "summaryBasis": "Publisher abstract and landing-page metadata; full methods not audited",
  "access": "Abstract-level evidence; dose, test methods and transferability require full-paper review. Not a universal finding about silanes.",
  "summaryAuthor": "Geopolymer Platform · AI-assisted discovery note",
  "id": "research-silane-ternary",
  "published": "2026-10-07",
  "title": "Impact of Silane Coupling Agent on the Basic Properties and Durability of Ternary Composite Geopolymer",
  "doi": "10.1007/s12633-026-03820-2",
  "journal": "Silicon",
  "topic": "Durability",
  "publisherUrl": "https://link.springer.com/article/10.1007/s12633-026-03820-2",
  "authors": "Jiesheng Liu, Taojie Song, Shengkun Tang, Yanxin Xiang and Ruijun Tang",
  "summary": "A slag, fly ash and metakaolin study finds that KH-560 changes workability while weakening the tested hardened material.",
  "highlights": [
    "Longer setting and greater fluidity accompanied the additive in this system.",
    "Higher additions reduced reported 28-day mechanical strength and resistance to freeze–thaw and sulfate exposure."
  ],
  "url": "https://doi.org/10.1007/s12633-026-03820-2"
},
{
  "year": 2026,
  "dateBasis": "Publisher version-of-record publication date",
  "type": "Research article",
  "publicationStatus": "Published; version of record",
  "checked": "2026-10-10",
  "added": "2026-10-10",
  "summaryBasis": "Publisher abstract and landing-page metadata; full methods not audited",
  "access": "Open access. Source-specific laboratory findings; no independent replication, unreported-age prediction or general environmental qualification established.",
  "summaryAuthor": "Geopolymer Platform · AI-assisted discovery note",
  "id": "research-treated-incinerator-bottom-ash",
  "published": "2026-10-03",
  "title": "Mechanical and microstructural properties of pre-treated incinerator bottom ash as fly ash replacement in alkali-activated materials",
  "doi": "10.1617/s11527-026-03289-w",
  "journal": "Materials and Structures",
  "topic": "Waste & biomass",
  "publisherUrl": "https://link.springer.com/article/10.1617/s11527-026-03289-w",
  "authors": "Muhammad Riaz Ahmad, Ahmed Mohamed Abbass, Jian-Guo Dai, Zhen Leng and Yanshuai Wang",
  "summary": "Water pretreatment changes the performance of incinerator bottom ash used to replace fly ash in an alkali-activated binder.",
  "highlights": [
    "The study compares untreated ash with ash immersed for ten days.",
    "At 20% fly-ash replacement, the treated-ash mixture retained control-level 28-day compressive strength."
  ],
  "url": "https://doi.org/10.1617/s11527-026-03289-w"
});
